### PR TITLE
Making JSDOM a direct dependency and adding hooks for patching JSDOM

### PR DESCRIPTION
**Pull request by ashimaathri**
You may have to remove the link jsdom-nocache from cloudbrowser/node_modules for this to work.

### CODE REVIEW

**Comment by godmar** [comment]
It says "This pull request cannot be automatically merged".  Not sure what to do then. Perhaps you need to redo it - perhaps pull and the rebase it on the last revision?

**Comment by godmar** [comment]
Also - I think it's best practice if you create a branch for each specific pull request. (Right now, you're offering to push your master branch).  I've learned that if you make subsequent commits on a branch that's involved in a pull request, those subsequent commits will contribute to/being counted as part of the same pull request.

**Comment by brianmcd** [comment]
Re: "This pull request cannot be automatically merged.", like @godmar said, if you rebase against brianmcd/master, you should be able to merge.  This message shows up if there will be merge conflicts when this branch is merged.

If you aren't familiar with git, the workflow would be something like:

```
git remote add brianmcd https://github.com/brianmcd/cloudbrowser.git
git checkout master
git pull --rebase brianmcd master
```

At this point, git will re-apply your changes and give you a chance to fix merge conflicts along the way.  Just follow the directions git tells you.  Most importantly, as you fix conflicts at each step and do git add, you do `git rebase --continue` instead of `git commit`.  If you get in trouble, you can do `git rebase --abort` and it'll take you back to where you were before you started the rebase.

After the rebase, you'll need to "force push" to your branch on github, since you re-wrote history:

```
git push -f origin master
```

This assumes that you have origin set up to be https://github.com/ashimaathri/cloudbrowser.git.  If origin is set up to be brianmcd/cloudbrowser, don't force push there :).

If you haven't done much rebasing, you might want to "back up" your current branch by doing `git checkout -b backup-master` from the branch you're going to rebase (looks like master in this case), and then you can switch back to master doing `git checkout master` and do your rebase.  You've also still got your changes here on github as long as you don't force push something bad.

Dr. Back's advice about putting each pull request on its own branch is definitely the way to go.

**Comment by ashimaathri** [comment]
Thanks for helping out Brian. Now I know about branching/merging/rebasing and I'll be able to create a new branch for every pull request :)
I've rebased against brianmcd/master. Will Dr. Back will be able to merge the pull request now?

**Comment by brianmcd** [comment]
No problem.  It looks like your pull request can be automatically merged now :).

**Pull request merged**
